title: CDC's Site
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of some of my favorite things.
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  cdcdatamaestro

show_excerpts: true # set to false to remove excerpts on the homepage
